### ISSUE TITLE
leaderboard column names

### ISSUE THREAD

**Issue by indonoso** [codalab/codalab-competitions#1182]
I keep getting this error when submitting a score to the leaderboard. 

``` python
Traceback (most recent call last):
  File "./apps/web/views.py", line 492, in get_context_data
    context['groups'] = phase.scores()
  File "./apps/web/models.py", line 715, in scores
    'resultLocation': result_location[count]
IndexError: list index out of range
```

My scores.txt file has this

nDCG: 0.0
MAP: 0.0
RMSE: 0.0

and the competition.yaml file has this

``` yaml
leaderboard:
    leaderboards:
        Ranking: &Ranking
            label: Ranking
            rank: 1
        Rating: &Rating
            label: Rating
            rank: 2
    columns:
        nDCG:
            leaderboard: *Ranking
            label: nDCG
            numeric_format: 3
            rank: 1
        MAP:
            leaderboard: *Ranking
            label: MAP
            numeric_format: 3
            rank: 2
        RMSE:
            leaderboard: *Rating
            label: RMSE
            numeric_format: 3
            rank: 1
```

What am I doing wrong?
