### ISSUE TITLE
Help needed by setting up scoring for LITS Challenge

### ISSUE THREAD

**Issue by PatrickChrist** [codalab/codalab-competitions#1669]
Hey Everyone,

I need your help in setting up the scoring for the LITS Challenge.

I followed your sample competitions about compute pi https://github.com/Tivix/competition-examples/tree/master/compute_pi and adjusted the example to calculate the metrics needed for this challenge. You can find my project and code here https://github.com/PatrickChrist/lits-challenge-scoring 
I tested it with sample data from the Challenge. which you can find in the Google Drive https://drive.google.com/drive/folders/0B0vscETPGI1-TkJubDBseEJhaGs?usp=sharing as reference.zip and submission.zip on my local setup. 

I created also a Test Environment on Codalab https://competitions.codalab.org/competitions/16223?secret_key=b21301f8-fd20-4c08-9d8f-c2343ff341a3
However the scoring did not work and could not produce a leaderboard entry. 
```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 313, in run
    os.mkdir(input_dir)
OSError: [Errno 2] No such file or directory: '/codalabtemp/tmpHV1Uye/run/input'
```
Would someone of the CodaLab Team be available for a call?

Thank you very much!
Best wishes,
Patrick

**Comment by jponttuset** [comment]
Have you tried running it more than once?
In my case, I get this error from time to time...
PS: I'm just a newbie user from Codalab

**Comment by PatrickChrist** [comment]
@jponttuset Thanks. It helped to rerun to come to the next error.
```
Traceback (most recent call last):
  File "/codalabtemp/tmp5JvP4L/run/program/evaluate.py", line 3, in <module>
    import nibabel as nb
ImportError: No module named nibabel
```
How can I install additional python packages? This would be the needed requirements:
https://github.com/PatrickChrist/lits-challenge-scoring/blob/master/requirements.txt

**Comment by jponttuset** [comment]
Cool! That's out of my experience already. :)
I hope someone from Codalab can help you with this.

**Comment by FlavioAlexander** [comment]
Hello @PatrickChrist I am having a hard time understanding your initial issue. Are you facing an issue during submissions or is it something else? For your second request, an organizer is not able to install packages. This is something that should be done by one of the codalab developers.

**Comment by PatrickChrist** [comment]
@FlavioAlexander My initial bug was solved by just re-running it. Regarding my second request: How can I get in touch with a codalab developer to setup my challenge properly?
Thanks for your help

**Comment by ckcollab** [comment]
@PatrickChrist hey Patrick, you just need us to install [these](https://raw.githubusercontent.com/PatrickChrist/lits-challenge-scoring/master/requirements.txt) requirements on the compute workers?

**Comment by PatrickChrist** [comment]
@ckcollab Yes, do you need more information from me? Thanks

**Comment by ckcollab** [comment]
https://competitions-test.codalab.org/

Could you please make your competition here and test it out? Thanks!

**Comment by PatrickChrist** [comment]
@ckcollab I created it at https://competitions-test.codalab.org/competitions/1364
If you want to test the submission you can use this as submission data https://drive.google.com/open?id=0B0vscETPGI1-UHZ2QXNPYmwxOWM

**Comment by PatrickChrist** [comment]
It still shows
```
Traceback (most recent call last):
  File "/codalabtemp/tmp5JvP4L/run/program/evaluate.py", line 3, in <module>
    import nibabel as nb
ImportError: No module named nibabel
```

**Comment by ckcollab** [comment]
Try now?

**Comment by PatrickChrist** [comment]
@ckcollab Thanks that worked! It is now calculating all metrics, which i can see in the view output log:
```
Starting with volume /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-2.nii
Found corresponding submission file /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-2.nii for reference file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-2.nii
Start calculating metrics for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-2.nii
Found following results for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-2.nii: {'voe': 0.1350930578161489, 'dice': 0.9275604295526126, 'rvd': -0.1350930578161489, 'assd': 0.31065490776718929, 'jaccard': 0.8649069421838511, 'msd': 5.589770387905209}
Starting with volume /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-1.nii
Found corresponding submission file /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-1.nii for reference file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-1.nii
Start calculating metrics for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-1.nii
Found following results for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-1.nii: {'voe': 0.6753024011554432, 'dice': 0.490221465076661, 'rvd': 2.0797887128162356, 'assd': 4.2450461147358318, 'jaccard': 0.3246975988445568, 'msd': 26.80707733045271}
Starting with volume /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-0.nii
Found corresponding submission file /codalabtemp/tmpFFsrUz/run/input/ref/segmentation-0.nii for reference file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-0.nii
Start calculating metrics for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-0.nii
Found following results for submission file /codalabtemp/tmpFFsrUz/run/input/res/segmentation-0.nii: {'voe': 0.5820967741935483, 'dice': 0.5894664998293709, 'rvd': 1.3928984947896565, 'assd': 6.9959650232432322, 'jaccard': 0.4179032258064516, 'msd': 159.37241496065317}
```
But the scoring error log shows: None
The submission is failed and no data is delivered to the leaderboard. Any ideas?

**Comment by ckcollab** [comment]
Hmm, none off the top of my head :(

**Comment by PatrickChrist** [comment]
Is it possible to see the scores.txt that has been created on the server to check for consistency?

**Comment by ckcollab** [comment]
Do you see the link for `"Download evaluation output from scoring step"`

![image](https://cloud.githubusercontent.com/assets/2185159/22536448/a634e6ca-e8b6-11e6-8d83-6f613a19539c.png)


That *should* have scores.txt, assuming you wrote it to the correct directory in your scoring program? Would you mind pasting some of the relevant code for writing the `scores.txt` file and maybe we can figure out what's wrong that way?

**Comment by PatrickChrist** [comment]
@ckcollab Thanks already for your help so far.
I think we are close:)
![image](https://cloud.githubusercontent.com/assets/5514132/22540811/af8488ea-e922-11e6-9550-bb8a7c149c76.png)
In comparision to you I dont see predict error and output log. And the private output log is not downloading.

But what looks good from my point is the scores.txt which i was able to download from Download evaluation output from scoring step. Here is it:
[patrickchrist-12-output.zip](https://github.com/codalab/codalab-competitions/files/747051/patrickchrist-12-output.zip)

The code the generate the scores is here: https://github.com/PatrickChrist/lits-challenge-scoring/blob/master/program/evaluate.py

I also added you and flavio as an admin to the codalab test project.
Thanks Patrick

**Comment by ckcollab** [comment]
> @ckcollab Thanks already for your help so far.
I think we are close:)

Woo! 👍 

Predict error/output are for code style submissions, where the submission is executed (prediction generated) and then scored.

>  And the private output log is not downloading.

I believe that is downloadable only when private output has been generated... I can't recall off the top of my head though.

**Comment by PatrickChrist** [comment]
@FlavioAlexander @ckcollab Do you have any ideas, how we can proceed? Is there a better way to debug? How can I ensure, that the creation of the scores.txt was correct? Is there a way to debug the mapping from scores.txt to leaderboard? Thank you

**Comment by ckcollab** [comment]
> How can I ensure, that the creation of the scores.txt was correct?

**Comment by PatrickChrist** [comment]
The output of the scoring program, which i can download looks fine for me. Here is the source code for saving the scores.txt. The full code is here https://github.com/PatrickChrist/lits-challenge-scoring/blob/master/program/evaluate.py
```
for reference_vol in reference_vol_list:

		print 'Starting with volume %s' % reference_vol

		reference_volume_path = reference_vol
		submission_volume_path = os.path.join(submit_dir, os.path.basename(reference_vol))
		if os.path.exists(submission_volume_path):
			print 'Found corresponding submission file %s for reference file %s' % (reference_volume_path,submission_volume_path)

			# Load Ref and submission with Nibabel
			loaded_reference_volume=nb.load(reference_volume_path)
			loaded_submission_volume = nb.load(submission_volume_path)

			# Get the current voxelspacing
			reference_voxelspacing= loaded_reference_volume.header.get_zooms()[:3]

			# Get Numpy data
			loaded_reference_volume_data = loaded_reference_volume.get_data()
			loaded_submission_volume_data = loaded_submission_volume.get_data()

			# Calc metric and store them in dict
			print 'Start calculating metrics for submission file %s' % submission_volume_path
			current_result = helpers.calc_metric.get_scores(loaded_submission_volume_data==2,loaded_reference_volume_data==2,reference_voxelspacing)

			print 'Found following results for submission file %s: %s' % (submission_volume_path,current_result)

			dice.append(current_result['dice'])
			voe.append(current_result['voe'])
			rvd.append(current_result['rvd'])
			assd.append(current_result['assd'])
			mssd.append(current_result['msd'])

	output_file.write("ISBIDiceComplete: %f\n" % np.mean(dice))
	output_file.write("ISBIVOEComplete: %f\n" % np.mean(voe))
	output_file.write("ISBIRVDComplete: %f\n" % np.mean(rvd))
	output_file.write("ISBIASSDComplete: %f\n" % np.mean(assd))
	output_file.write("ISBIMSSDComplete: %f\n" % np.mean(mssd))
	output_file.write("ISBIRankComplete: %f\n" % (np.mean(dice)+2-np.mean(voe)+np.mean(rvd)/3.))

	output_file.write("LBDiceComplete: %f\n" % np.mean(dice))
	output_file.write("LBVOEComplete: %f\n" % np.mean(voe))
	output_file.write("LBRVDComplete: %f\n" % np.mean(rvd))
	output_file.write("LBASSDComplete: %f\n" % np.mean(assd))
	output_file.write("LBMSSDComplete: %f\n" % np.mean(mssd))
	output_file.write("LBRankComplete: %f\n" % (np.mean(dice) + 2 - np.mean(voe) + np.mean(rvd) / 3.))

	output_file.close()
```
[scores.txt](https://github.com/codalab/codalab-competitions/files/755044/scores.txt)

**Comment by FlavioAlexander** [comment]
By looking at `scores.tx`t and evaluate script, they seem to match correctly. 🤔 @ckcollab I took a quick look at the logs file and we getting this error:

 ```2017-02-06 15:50:52,786 ERROR Failed to update submission (job_id=13049, submission_id=11451, status=finished)
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/apps/web/tasks.py", line 553, in update_it
    result = update_submission(submission, status, job.id, traceback, metadata)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/tasks.py", line 463, in update_submission
    SubmissionScore.objects.create(result=submission, scoredef=scoredef, value=float(value))
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
    return self.get_query_set().create(**kwargs)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 416, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/models.py", line 1774, in save
    raise IntegrityError("Score is computed. Cannot assign a value")
IntegrityError: Score is computed. Cannot assign a value
2017-02-06 15:50:52,787 ERROR An error occurred during task execution (job_id=13049).
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/apps/jobs/models.py", line 234, in run_job_task
    result = computation(job)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/tasks.py", line 557, in update_it
    raise SubmissionUpdateException(submission, e)
SubmissionUpdateException: Score is computed. Cannot assign a value```

**Comment by ckcollab** [comment]
```SubmissionUpdateException: Score is computed. Cannot assign a value```

Hmm, thanks for looking into this @FlavioAlexander! Always appreciate your help.

What does your leaderboard definition look like? Are you setting a column to be "computed", but at the same time providing a value for that column?

**Comment by PatrickChrist** [comment]
@ckcollab That is maybe the reason. Probabily the leaderboard definition is messed up. Here it is attached. 
```
leaderboard:
    leaderboards:
        ISBI: &ISBI
            label: ISBI
            rank: 1
        LB: &LB
            label: Open leaderboard
            rank: 2

    column_groups:
        Dice: &DICE
            label: Dice
        VOE: &VOE
            label: Volume Overlab Error
        RVD: &RVD
            label: Relative Volume Difference
        ASSD: &ASSD
            label: Average symmetric surface distance
        MSSD: &MSSD
            label: Maximum symmetric surface distance
        RANK: &RANK
            label: Final Score

    columns:
        ISBIDiceComplete: 
            leaderboard: *ISBI
            column_group: *DICE
            label: Average
            rank: 1
            numeric_format: 3
        ISBIVOEComplete: 
            leaderboard: *ISBI
            column_group: *VOE
            label: Complete
            rank: 1
            numeric_format: 3
        ISBIRVDComplete: 
            leaderboard: *ISBI
            column_group: *RVD
            label: Complete
            rank: 1
            numeric_format: 3
        ISBIASSDComplete: 
            leaderboard: *ISBI
            column_group: *ASSD
            label: Complete
            rank: 1
            numeric_format: 3
        ISBIMSSDComplete: 
            leaderboard: *ISBI
            column_group: *MSSD
            label: Complete
            rank: 1
            numeric_format: 3
        ISBIRankComplete: 
            leaderboard: *ISBI
            column_group: *RANK
            label: Complete
            rank: 1
            numeric_format: 3
            computed:
              operation: Avg
              fields: ISBIDiceComplete, ISBIVOEComplete, ISBIRVDComplete, ISBIASSDComplete, ISBIMSSDComplete

        LBDiceComplete: 
            leaderboard: *LB
            column_group: *DICE
            label: Average
            rank: 1
            numeric_format: 3
        LBVOEComplete: 
            leaderboard: *LB
            column_group: *VOE
            label: Complete
            rank: 1
            numeric_format: 3
        LBRVDComplete: 
            leaderboard: *LB
            column_group: *RVD
            label: Complete
            rank: 1
            numeric_format: 3
        LBASSDComplete: 
            leaderboard: *LB
            column_group: *ASSD
            label: Complete
            rank: 1
            numeric_format: 3
        LBMSSDComplete: 
            leaderboard: *LB
            column_group: *MSSD
            label: Complete
            rank: 1
            numeric_format: 3
        LBRankComplete: 
            leaderboard: *LB
            column_group: *RANK
            label: Complete
            rank: 1
            numeric_format: 3
            computed:
              operation: Avg
              fields: LBDiceComplete, LBVOEComplete, LBRVDComplete, LBASSDComplete, LBMSSDComplete
```

**Comment by ckcollab** [comment]
Hmm, got this error running a submission locally.. maybe I didn't put in the right scoring program?

```
/Users/eric/.virtualenvs/codalab-competitions/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/eric/.virtualenvs/codalab-competitions/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by PatrickChrist** [comment]
Mmh this does not look like a error, which comes from my code. Did you installed the packages mentioned here? https://github.com/PatrickChrist/lits-challenge-scoring/blob/master/requirements.txt
Have you used this scoring program?
https://github.com/PatrickChrist/lits-challenge-scoring/tree/master/program

This program was able to produce a result, which i could send to the leaderboard in https://competitions-test.codalab.org/competitions/1369 But the leaderboard display says: 
```
There is a problem with the leaderboard

Are all of the leaderboard column names matched with scores saved in scores.txt?

Traceback (most recent call last):
  File "./apps/web/views.py", line 574, in get_context_data
    context['groups'] = phase.scores()
  File "./apps/web/models.py", line 858, in scores
    'resultLocation': result_location[count]
IndexError: list index out of range
```

**Comment by ckcollab** [comment]
Hmm... well I see this error that may be hidden from you on my end:

```
DatabaseError: (1366, "Incorrect decimal value: 'NaN' for column 'value' at row 1")
```

This seems to be the culprit:

```
Attempting to submit score ISBIDiceComplete: nan
```

Apologies for taking so long to get back to you on this, having a few troubles with new compute workers queues that I'm working through :)

**Comment by PatrickChrist** [comment]
@ckcollab Which submission file did you use? This is the one which works. https://drive.google.com/file/d/0B0vscETPGI1-UHZ2QXNPYmwxOWM/view Does the scores.txt also shows NaN for you with this submission file? If not, it could be some issue with floating point accuracy?
```
    columns:
        ISBIDiceComplete: 
            leaderboard: *ISBI
            column_group: *DICE
            label: Average
            rank: 1
            numeric_format: 3
```
Says "numeric_format:3" and the scores.txt has a longer floating point accuracy.
```
ISBIDiceComplete: 0.669083
ISBIVOEComplete: 0.464164
ISBIRVDComplete: 1.112531
ISBIASSDComplete: 3.850555
ISBIMSSDComplete: 63.923088
LBDiceComplete: 0.669083
LBVOEComplete: 0.464164
LBRVDComplete: 1.112531
LBASSDComplete: 3.850555
LBMSSDComplete: 63.923088
```
What do you think?
