### ISSUE TITLE
Creating new competition gives non-meaningful error message: 'data'

### ISSUE THREAD

**Issue by nightrome** [codalab/codalab-competitions#2320]
Hi, I am trying to create a new challenge and after uploading the zip bundle it gives me the error message 

> Oops! There was a problem creating the competition:  'data'

I have also tried taking today's dump from [my previous challenge](https://competitions.codalab.org/competitions/17443), which results in the same error. Any ideas why this is? I noticed that a number of things changed on Codalab since I created the previous challenge (Sept. 2017).

This is the yaml file I am uploading:
```
title: COCO 2018 Stuff Segmentation Challenge
description: This challenge is designed to push the state of the art in semantic segmentation
  of stuff classes.
start_date: 2018-06-30 00:00:00+00:00
end_date: 2050-01-01 00:00:00+00:00
competition_docker_image: False
image: logo.png
has_registration: True
force_submission_to_leaderboard: False
disallow_leaderboard_modifying: False
enable_detailed_results: True
admin_names: null
html:
  evaluation: evaluation.html
  overview: overview.html
  terms: terms.html
phases:
  0:
    auto_migration: null
    color: white
    datasets:
      0:
        description: ''
        name: Data 1
        url: http://cocodataset.org
    description: The two example images provided in the COCO Stuff API repository.
      The results file can be created by running the pngToCocoResultDemo script. Evaluation
      should take approximately 2 minutes.
    is_scoring_only: true
    label: examples
    max_submissions: 999
    max_submissions_per_day: 999
    phasenumber: 1
    reference_data: reference_data_1.zip
    scoring_program: scoring_program_1.zip
    start_date: 2018-06-30 00:00:00+00:00
leaderboard:
  columns:
    FIOU:
      label: FIOU
      leaderboard: &id001
        label: Results
        rank: 1
      rank: 1
      sort: desc
    FIOUS:
      label: FIOUS
      leaderboard: *id001
      rank: 1
      sort: desc
    MACC:
      label: MACC
      leaderboard: *id001
      rank: 1
      sort: desc
    MACCS:
      label: MACCS
      leaderboard: *id001
      rank: 1
      sort: desc
    MIOU:
      label: MIOU
      leaderboard: *id001
      rank: 1
      sort: desc
    MIOUS:
      label: MIOUS
      leaderboard: *id001
      rank: 1
      sort: desc
    PACC:
      label: PACC
      leaderboard: *id001
      rank: 1
      sort: desc
    PACCS:
      label: PACCS
      leaderboard: *id001
      rank: 1
      sort: desc
  leaderboards:
    Results: *id001
```

**Comment by Tthomas63** [comment]
Hello @nightrome,

Sorry for the inconvenience you've experienced, however it should be an easy fix!

The main cause of the error you're seeing is a required html file is not defined in your YAML for your competition. The reason the error reads `'data'` is because that is the missing key-name is it looking for. The error can be fixed by adding a key called `data` to the HTML fields, with a value of the name of your desired html file. (See YAML below) The HTML file itself can be blank in this case I believe.

I've also identified a bug in the competition dump process that makes any boolean field that is currently `False`, output as `null` which causes issues in the un-packing process. This is why your competition dump wasn't working, and I should have a fix for this shortly.

There was also some minor syntax errors in your YAML file that may have been causing some issues for the interpreter.  Here's the YAML file I had working for testing: 

```
title: COCO 2018 Stuff Segmentation Challenge
description: This challenge is designed to push the state of the art in semantic segmentation of stuff classes.
start_date: 2018-06-30 00:00:00+00:00
end_date: 2050-01-01 00:00:00+00:00
competition_docker_image: ''
image: logo.png
has_registration: true
force_submission_to_leaderboard: false
disallow_leaderboard_modifying: false
enable_detailed_results: true
admin_names: null
html:
  evaluation: evaluation.html
  overview: overview.html
  terms: terms.html
  data: data.html
phases:
  0:
    auto_migration: false
    color: white
    datasets:
      0:
        description: null
        name: Data 1
        url: http://cocodataset.org
    description: The two example images provided in the COCO Stuff API repository. The results file can be created by running the pngToCocoResultDemo script. Evaluation should take approximately 2 minutes.
    is_scoring_only: true
    label: examples
    max_submissions: 999
    max_submissions_per_day: 999
    phasenumber: 1
    reference_data: reference_data_1.zip
    scoring_program: scoring_program_1.zip
    start_date: 2018-06-30 00:00:00+00:00
leaderboard:
  columns:
    FIOU:
      label: FIOU
      leaderboard: &id001
        label: Results
        rank: 1
      rank: 1
      sort: desc
    FIOUS:
      label: FIOUS
      leaderboard: *id001
      rank: 1
      sort: desc
    MACC:
      label: MACC
      leaderboard: *id001
      rank: 1
      sort: desc
    MACCS:
      label: MACCS
      leaderboard: *id001
      rank: 1
      sort: desc
    MIOU:
      label: MIOU
      leaderboard: *id001
      rank: 1
      sort: desc
    MIOUS:
      label: MIOUS
      leaderboard: *id001
      rank: 1
      sort: desc
    PACC:
      label: PACC
      leaderboard: *id001
      rank: 1
      sort: desc
    PACCS:
      label: PACCS
      leaderboard: *id001
      rank: 1
      sort: desc
  leaderboards:
    Results: *id001
```

Please let me know if you're still experiencing issues after trying the above YAML changes.
Thanks, and best regards,
Tyler
