### ISSUE TITLE
[Feature request] Weighted average ranking on multi-tasks leaderboard

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2758]
We can rank participants with the average ranking on several scores using something like this:

```
leaderboard:
  columns:
    auc_binary:
      label: Classification (AUC ROC)
      leaderboard: &id001
        label: RESULTS
        rank: 1
      rank: 2
      sort: desc
    auc_binary_2:
      label: Feature Selection (AUC ROC)
      leaderboard: *id001
      rank: 3
      sort: desc
    ave_score:
      label: < Rank >
      leaderboard: *id001
      rank: 1
      sort: asc
      computed:
        operation: Avg
        fields: auc_binary, auc_binary_2
  leaderboards:
    RESULTS: *id001
```

But some organizers would like to be able to be able to compute an weighted average ranking, let's say: **Task_A_rank * 0.4 + Task_B_rank * 0.6**

We can see in this piece of code from Codalab that the current operation implemented are average and maximum:

```
class SubmissionComputedScore(models.Model):
    scoredef = models.OneToOneField(SubmissionScoreDef, related_name='computed_score')
    operation = models.CharField(max_length=10, choices=(('Max', 'Max'),
                                                        ('Avg', 'Average')))
```

The coefficient in the weighted average would represent the importance of each sub-task.
