### ISSUE TITLE
scores on competition page are either 0 or 1. 

### ISSUE THREAD

**Issue by TalitaAnthonio** [codalab/codalab-competitions#2995]
Link to competition: https://competitions.codalab.org/competitions/35041?secret_key=558f4e05-d034-4cc1-91ad-2c6c91fb5613

I have problems with my scoring program. For some reason, the scores.txt file only contains: 
```
accuracy_score:0 
```
or 
```
accuracy_score:1
```

When I run the evaluation script on my computer, I get accuracy scores between 0 and 1 (accuracy_score:0.75). 

I think the .yaml file is also correct: 

```
leaderboard:
    leaderboards:
        RESULTS: &RESULTS
            label: Results
            rank: 1
    columns:
        accuracy_score:
            leaderboard: *RESULTS
            label: Accuracy Score
            rank: 2
            numeric_format: 5

```

And this is the evaluation script that I am using: 

```


#!/usr/bin/env python

import sys
import os
import os.path
import pandas as pd 


# read the files? 
input_dir = sys.argv[1]
output_dir = sys.argv[2]

submit_dir = os.path.join(input_dir, 'res')
truth_dir = os.path.join(input_dir, 'ref')



if not os.path.isdir(submit_dir):
    print("Doesn't exist {0}".format(submit_dir))

if os.path.isdir(submit_dir) and os.path.isdir(truth_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)


    # write the score to the output file. 
    output_filename = os.path.join(output_dir, 'scores.txt')
    output_file = open(output_filename, 'w')


    # read the files 
    truth_file = os.path.join(truth_dir, "truth.tsv")
    truth = pd.read_csv(truth_file, sep='\t')
    truth_dict = {row["Id"]: row["Class"] for index,row in truth.iterrows()}
    

    # read the submission answer file and compute accuracy. 
    submission_answer_file = os.path.join(submit_dir, "answers.tsv")
    submission_answer = pd.read_csv(submission_answer_file, sep='\t')
    submission_answer_dict = {row["Id"]: row["Class"] for index, row in submission_answer.iterrows()}


    # compute the accuracy: 
    results = []
    for id, answer in submission_answer_dict.items(): 
        #sys.stdout.write(submission_answer_dict[id] + ' ' + truth_dict[id] + '\n')
        if submission_answer_dict[id] == truth_dict[id]: 
           #output_file.write("correct:1 {0}".format("\n"))    
           results.append(1)

        else:
            #output_file.write("correct:0 {0}".format("\n"))
            results.append(0)


    assert len(results) != 0 
    accuracy_score = (sum(results) / len(results))*100
    output_file.write("accuracy_score:{0}".format(accuracy_score))
    output_file.close()


```

What's going on here?
