### ISSUE TITLE
Debugging as organizer: submission fails with no error message

### ISSUE THREAD

**Issue by vzhong** [codalab/codalab-competitions#3284]
I am running into a submission failed problem with no error message for my competition here:
https://codalab.lisn.upsaclay.fr/competitions/8591

I have added the requested users as admins.

I see no error message is stderr.txt. When I download the output zip, I see that `metadata` shows an exit status of 0, which seems to suggest that the job has completed. I imagine that something is breaking after the job completes. Maybe parsing the score file? Anyway, there is no error so I cannot figure out why.

I see that `score.txt` has the following:

```
open_dev_complete_f1_@kNone: 0.035327734807436624
open_dev_complete_cluster_min_f1_@kNone: 0.0034285428567659634
open_dev_complete_precision_@k1: 0.10887843807895112
open_dev_complete_cluster_min_precision_@k1: 0.00768775872264932
open_dev_complete_precision_@k10: 0.0974106534923126
open_dev_complete_cluster_min_precision_@k10: 0.0066479400749063665
open_dev_complete_precision_@k100: 0.095859417426791
open_dev_complete_cluster_min_precision_@k100: 0.00671630098005024
open_test_complete_f1_@kNone: 0.04064745014136525
open_test_complete_cluster_min_f1_@kNone: 0.004437379148566088
open_test_complete_precision_@k1: 0.11093277945619336
open_test_complete_cluster_min_precision_@k1: 0.005516154452324665
open_test_complete_precision_@k10: 0.10013307437778782
open_test_complete_cluster_min_precision_@k10: 0.008778315634107598
open_test_complete_precision_@k100: 0.0987010286145946
open_test_complete_cluster_min_precision_@k100: 0.008742487447014769
```

My config file:

```
leaderboard:
    leaderboards:
        RESULTS: &RESULTS
            label: Open setting results
            rank: 1
    columns:
        open_test_complete_f1_@kNone:
            leaderboard: *RESULTS
            label: test F1
            rank: 1
            numeric_format: 3
        open_test_complete_cluster_min_f1_@kNone:
            leaderboard: *RESULTS
            label: test robust F1
            rank: 2
            numeric_format: 3
        open_test_complete_precision_@k1:
            leaderboard: *RESULTS
            label: test precision@1
            rank: 3
            numeric_format: 3
        open_test_complete_cluster_min_precision_@k1:
            leaderboard: *RESULTS
            label: test robust precision@1
            rank: 4
            numeric_format: 3
        open_test_complete_precision_@k10:
            leaderboard: *RESULTS
            label: test precision@10
            rank: 5
            numeric_format: 3
        open_test_complete_cluster_min_precision_@k10:
            leaderboard: *RESULTS
            label: test robust precision@10
            rank: 6
            numeric_format: 3
        open_test_complete_precision_@k100:
            leaderboard: *RESULTS
            label: test precision@100
            rank: 7
            numeric_format: 3
        open_test_complete_cluster_min_precision_@k100:
            leaderboard: *RESULTS
            label: test robust precision@100
            rank: 8
            numeric_format: 3
        open_dev_complete_f1_@kNone:
            leaderboard: *RESULTS
            label: dev F1
            rank: 9
            numeric_format: 3
        open_dev_complete_cluster_min_f1_@kNone:
            leaderboard: *RESULTS
            label: dev robust F1
            rank: 10 
            numeric_format: 3
        open_dev_complete_precision_@k1:
            leaderboard: *RESULTS
            label: dev precision@1
            rank: 11
            numeric_format: 3
        open_dev_complete_cluster_min_precision_@k1:
            leaderboard: *RESULTS
            label: dev robust precision@1
            rank: 12
            numeric_format: 3
        open_dev_complete_precision_@k10:
            leaderboard: *RESULTS
            label: dev precision@10
            rank: 13
            numeric_format: 3
        open_dev_complete_cluster_min_precision_@k10:
            leaderboard: *RESULTS
            label: dev robust precision@10
            rank: 14
            numeric_format: 3
        open_dev_complete_precision_@k100:
            leaderboard: *RESULTS
            label: dev precision@100
            rank: 15
            numeric_format: 3
        open_dev_complete_cluster_min_precision_@k100:
            leaderboard: *RESULTS
            label: dev robust precision@100
            rank: 16
            numeric_format: 3
```
