### ISSUE TITLE
Competition YAML more HTML pages

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#494]
Currently you are limited to the 4 HTML page options: `overview`, `evaluation`, `terms`, and `data`.

Example:

``` yaml
html: 
    overview: overview.html
    evaluation: evaluation.html
    terms: terms_and_conditions.html
    data: data.html
```

It would be nice to be able to say `any label` and tie that to any HTML file.

Example:

``` yaml
html: 
    overview: overview.html
    evaluation: evaluation.html
    terms: terms_and_conditions.html
    data: data.html
    my_new_page: some_page.html
```
