### ISSUE TITLE
Grouping bundles into super-bundles

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#497]
Instead of doing:

```
phases:
    1:
        input: test.zip
        reference_data: ref_data.zip
```

Do

```
phases:
    1:
        input:
            1:
                data: test.zip
            2:
                data: test2.zip

        reference_data:
            1:
                data: ref_test_1.zip
            2:
                data: ref_test_2.zip
```

And in the evaluation program you would get:

```
input/1/test.zip
input/2/test2.zip
```
